version: '2'
services:
  kavsir-app:
    image: kavsir
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://kavsir-postgresql:5432/kavsir
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://kavsir-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://kavsir-elasticsearch:9200
    ports:
      - 8080:8080
  kavsir-postgresql:
    extends:
      file: postgresql.yml
      service: kavsir-postgresql
  kavsir-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: kavsir-elasticsearch
